### ISSUE TITLE
我用maven项目导入web3，生成签名的时候signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by fanchi1** [ethjava/web3j-sample#9]
Exception in thread "main" java.lang.SecurityException: class "org.bouncycastle.jcajce.provider.digest.BCMessageDigest"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.web3j.abi.FunctionEncoder.buildMethodId(FunctionEncoder.java:88)
	at org.web3j.abi.FunctionEncoder.encode(FunctionEncoder.java:28)
	at walletmanager.ETHTest.tranToken(ETHTest.java:448)
	at walletmanager.ETHTest.main(ETHTest.java:76)

**Comment by fanchi1** [comment]
不知道是啥原因！实在找不出来

**Comment by TOTOROYang** [comment]
[找到个类似的错误](http://blog.sina.com.cn/s/blog_4afee0940100v1u6.html) 可能是jar冲突什么的
